---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: AWS Lambda event source: Kinesis data stream'
# cfn-modules:implements()
Parameters:
  LambdaModule:
    Description: 'Stack name of lambda-function module.'
    Type: String
  DataStreamModule:
    Description: 'Stack name of kinesis-data-stream module.'
    Type: String
  BatchSize:
    Description: 'The largest number of messages that Lambda retrieves from your stream at once.'
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 10000
  StartingPosition:
    Description: 'The position in the stream where Lambda starts reading.'
    Type: String
    Default: LATEST
    AllowedValues: [LATEST, TRIM_HORIZON]
Resources:
  Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
      - 'Fn::ImportValue': !Sub '${LambdaModule}-RoleName'
      PolicyName: !Join ['', ['cfn-modules-', {'Fn::ImportValue': !Sub '${DataStreamModule}-Name'}]] # ASCII characters minus the following reserved characters: backward slash (\), forward slash (/), asterisk (*), question mark (?), and white space
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 'kinesis:DescribeStream'
          - 'kinesis:GetRecords'
          Resource: {'Fn::ImportValue': !Sub '${DataStreamModule}-Arn'}
        - Effect: Allow
          Action:
          - 'kinesis:GetShardIterator' # TODO double check with support if resource level constraints are not supported
          - 'kinesis:ListStreams'
          Resource: '*'
  EventSourceMapping:
    DependsOn: Policy
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: !Ref BatchSize
      Enabled: true
      EventSourceArn: {'Fn::ImportValue': !Sub '${DataStreamModule}-Arn'}
      FunctionName: {'Fn::ImportValue': !Sub '${LambdaModule}-Arn'}
      StartingPosition: !Ref StartingPosition
Outputs:
  ModuleId:
    Value: 'lambda-event-source-kinesis-data-stream'
  ModuleVersion:
    Value: '0.1.0'
  StackName:
    Value: !Ref 'AWS::StackName'
